### ISSUE TITLE
Renaming Suggestion of Method Names to Make Them More Descriptive

### ISSUE THREAD

**Issue by AnonymousAccount4SE** [saahilanande/Backend-MTRS#18]
### Renaming Suggestion of Method Names to Make Them More Descriptive
---
**Description**
---
As one of the most important types of identifiers, method names play an essential role in program comprehension and maintenance. As a result, method names should be clear, concise, and descriptive of the functionality of method bodies.

To identify non-descriptive method names, we have developed a DL-based tool named **NameSpotter**, and we would like to help you with identifying non-descriptive method names in your projects.

We inspect all the Java method names in your project and find that the majority of them are descriptive enough to deliver the functionality of the corresponding bodies. However, there are still some method names that **NameSpotter** considered non-descriptive. 
Here we give an example of non-descriptive method names in your projects:
```java
/* Non-descriptive Method Names in src/main/java/org/saahilmakes/BackendMTRS/Config/SecurityConfig.java */
public AuthenticationManager customAuthenticationManager(HttpSecurity http) throws Exception {
        AuthenticationManagerBuilder authenticationManagerBuilder = http.getSharedObject
                (AuthenticationManagerBuilder.class);
        authenticationManagerBuilder.userDetailsService(userSecurity)
                .passwordEncoder(bCryptPasswordEncoder());
        return authenticationManagerBuilder.build();
    }

```
NameSpotter considered "customAuthenticationManager" as non-descriptive because it lacks a verb indicating the action of this method, and we proposed renaming the method name to "customizeAuthenticationManager". Consequently, when we look at this method name, we will be informed that this method customizes an AuthenticationManager object and possibly returns it.

Do you agree with the judgment of **NameSpotter**? 

- If not, could you please leave a comment for us to improve?

- If you do agree, the relevant modification has been submitted as a PR, and thanks for your precious time to consider it.

**Comment by saahilanande** [comment]
Thanks for your suggestion.

**Comment by AnonymousAccount4SE** [comment]
You are welcome! Thanks for your precious time!
